worker_processes  1;

events {
    worker_connections  1024;
}

http {
    upstream gateway_grpc_backend {
        least_conn;
        server gateway-1:19080;
        server gateway-2:19080;
        keepalive 64;
    }

    server {
        listen 80 http2;

        location = /healthz {
            return 200 "ok\n";
        }

        location /sessionrpc.GatewayService/ {
            grpc_pass grpc://gateway_grpc_backend;
            grpc_read_timeout 3600s;
            grpc_send_timeout 3600s;
            client_body_timeout 3600s;
        }
    }
}
